title: André Leitzke
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A space for occasional thoughts.
  Believe me, they do happen every now and then!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leitzke.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  leitzke-andre

# Build settings
theme: minima
plugins:
  - jekyll-feed

mastodon:
- username: leitzke
  instance: hachyderm.io